name: ML Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        pytest tests/ --cov=./ --cov-report=xml
    
    - name: Upload coverage
      uses: codecov/codecov-action@v2

  train:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train retail model
      run: |
        python retail_analysis.py --data_path data/retail_data.xlsx
    
    - name: Train wholesale model
      run: |
        python wholesale_analysis.py --data_path data/wholesale_data.csv
    
    - name: Upload models
      uses: actions/upload-artifact@v2
      with:
        name: trained-models
        path: |
          models/*.pth
          models/*.joblib

  deploy:
    needs: train
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download models
      uses: actions/download-artifact@v2
      with:
        name: trained-models
        path: models/
    
    - name: Deploy to staging
      run: |
        # Add your deployment script here
        echo "Deploying models to staging environment"